### ISSUE TITLE
Section 13.2. Symmetric Keys talks about private keys

### ISSUE THREAD

**Issue by LudwigSeitz** [cose-wg/cose-spec#149]
In Section 13.2. there is the following text: "This key structure contains only private key information, care must  be taken that it is never transmitted accidentally.  For public keys,  there are no required fields.  For private keys, it is REQUIRED that 'k' be present in the structure."

This should probably read something like this:
"This key structure only contains secret (or symmetric) key information, care must be taken that it is never transmitted accidentally. For symmetric keys, it is REQUIRED that 'k' be present in the structure."

**Comment by jimsch** [comment]
What if we change it to be 

This key structure does not have a form that contains only public members.  For symmetric keys, it is REQUIRED that 'k' be present in the structure.

**Comment by LudwigSeitz** [comment]
I really have nothing against the "care must be taken ..." part. I'd actually tend to leave it in, but feel free to rephrase that as you see fit.
